### ISSUE TITLE
Error while reading pdf

### ISSUE THREAD

**Issue by manish59** [izderadicka/pdfparser#19]
import pdfparser.poppler as pdf

 pdf.Document(r"Manish.pdf")
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "pdfparser/poppler.pyx", line 116, in pdfparser.poppler.Document.__cinit__
TypeError: expected bytes, str found

Its in redhat
Can anyone help to fix this please.

**Comment by izderadicka** [comment]
I'm assuming you're using python 3, right? - please confirm version.
Currently file name is  `char*`,  which means bytes in python3 -   so you should use
`pdf.Document(b"Manish.pdf")`

In future versions we should improve interface to accept also strings in Python 3.

**Comment by manish59** [comment]
Yes Im using in python. Its working. But the rgb values which Im getting are like this   r:0.89 g:0.42, b:0.04 but when i check its not showing the same color i need. Do I need to do any thing here to get actucal rgb values in range of 0-255

**Comment by manish59** [comment]
Actually I figured the color space. You can close this issue. Thanks for helping though. Can we detect any hyperlinks using this tool

**Comment by manish59** [comment]
Can we use this library in windows ?

**Comment by izderadicka** [comment]
See #17 - theoretically yes, but requires advanced win,python, c++ skills.

I'm keeping this open as there is potential improvement for python 3.

**Comment by manish59** [comment]
can we detect hyperlinks using this tool
